[program:postgresql]
command=/app/scripts/start_postgres.sh
user=root
autostart=true
autorestart=true
stdout_logfile=/app/pglogs/pg_supervisor.log
stderr_logfile=/app/pglogs/pg_supervisor_err.log
priority=1
